TRUNCATE TABLE votes RESTART IDENTITY AND COMMIT;
TRUNCATE TABLE users RESTART IDENTITY AND COMMIT;
TRUNCATE TABLE roles RESTART IDENTITY AND COMMIT;
TRUNCATE TABLE menu_sets RESTART IDENTITY AND COMMIT;
TRUNCATE TABLE restaurants RESTART IDENTITY AND COMMIT;
TRUNCATE TABLE lunch_menu RESTART IDENTITY AND COMMIT;
TRUNCATE TABLE dishes RESTART IDENTITY AND COMMIT;

INSERT INTO ROLES VALUES
  (1, 'ROLE_ADMIN'),
  (2, 'ROLE_REGULAR');

INSERT INTO USERS (ID, ROLES_ID, NAME, EMAIL, PASSWORD) VALUES
  (1, 1, 'User1', 'user1@gmail.com', 'password1'),
  (2, 2, 'User2', 'user2@gmail.com', 'password2');

INSERT INTO DISHES (ID, NAME, PRICE) VALUES
  (1, 'dish1', 10000),
  (2, 'dish2', 100000);

INSERT INTO LUNCH_MENU (ID, NAME) VALUES
  (1, 'menu1'),
  (2, 'menu2');

INSERT INTO MENU_SETS (ID, LUNCH_MENU_ID, DISH_ID, DAY) VALUES
  (1, '1', '1', 1),
  (2, '1', '2', 1),
  (3, '1', '1', 2),
  (4, '1', '1', 3);

INSERT INTO RESTAURANTS (ID, LUNCH_MENU_ID, NAME, RATING) VALUES
  (1, 1, 'restaurant1', 0),
  (2, 1, 'restaurant2', 0);

INSERT INTO VOTES (ID, RESTAURANT_ID, USER_ID, up, DATE) VALUES
  (1, 1, '1', 1, '2018-02-04');
INSERT INTO VOTES (ID, RESTAURANT_ID, USER_ID, up, DATE) VALUES
  (2, 1, '1', 0, '2018-04-04');